# flask配置
FLASK_APP=app.py
FLASK_ENV=development
FLASK_DEBUG=1
FLASK_RUN_HOST = 127.0.0.1
FLASK_RUN_PORT = 5000

#flask配置
SYSTEM_NAME =Fishs

# MySql配置信息
MYSQL_HOST=
MYSQL_PORT=3306
MYSQL_DATABASE=hhuFishes
MYSQL_USERNAME=root
MYSQL_PASSWORD=

# 密钥配置(记得改)
SECRET_KEY='hhu-fishes'

# 邮箱配置
MAIL_SERVER='smtp.qq.com'
MAIL_USERNAME='123@qq.com'
MAIL_PASSWORD='XXXXX' # 生成的授权码